# These are supported funding model platforms

# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
github: # username

# Replace with a single Patreon username
patreon: # username

# Replace with a single Open Collective username
open_collective: alapnian

# Replace with a single Ko-fi username
ko_fi: # username

# Replace with a single Tidelift platform-name/package-name e.g., npm/babel
tidelift: # platform-name/package-name

# Replace with a single Community Bridge project-name e.g., cloud-foundry
community_bridge: # project-name

# Replace with a single Liberapay username
liberapay: # username

# Replace with a single IssueHunt username
issuehunt: # username

# Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
lfx_crowdfunding: #project-name

# Replace with a single Polar username
polar: # username

# Replace with a single Buy Me a Coffee username
buy_me_a_coffee: # username

# Replace with a single thanks.dev username
thanks_dev: # username

# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
custom: # ['link1', 'link2']
